### PR TITLE
Fix crash without extension on Rococo

### LINKED ISSUE #305: App breaks if extension is not installed
**To Reproduce**

1. Start the app in a browser where the Polkadot extension is not installed. 
2. Connect to Contracts on Rococo
3. Go to` /instantiate`
4. Page tries to get keyring accounts to render the `AccountSelect`, but a white screen is displayed because the keyring is not initialised

**Expected behavior**
The app should check the Polkadot extension is installed and if it's not, display a modal. The user should import or create a Substrate account before using the app

Connect Modal
Connect Modal

### PR DESCRIPTION
**Pull request by kwingram25**
Closes #305

- Sets default accountId value correctly without crashing in event that Polkadot extension is not found
- Display blocking error message with instructions to install extension, in case no accounts found on a testnet

### CODE REVIEW

File: src/ui/components/AwaitApis.tsx [hunk 1]
```diff
@@ -20,9 +21,13 @@ export function AwaitApis({ children }: HTMLAttributes<HTMLDivElement>): React.R
     status !== 'READY' && setMessage(`Connecting to ${endpoint}...`);
   }, [db, keyringStatus, status, endpoint]);
 
-  return (
-    <>
-      {error ? <ConnectionError /> : isLoading ? <Loader message={message} isLoading /> : children}
-    </>
-  );
+  if (keyringStatus === 'READY' && keyring?.getAccounts().length === 0) {
```
Comment (statictype) [inline src/ui/components/AwaitApis.tsx:24]: I think we should display 2 separate messages for:
1. Extension not installed
2. Extension installed but no accounts

Right now it's a bit confusing that after installing the extension I get the same message.

File: src/ui/components/common/AccountsError.tsx [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+          <li>
+            Follow{' '}
+            <a
+              rel="noopener noreferrer"
+              target="_blank"
+              href="https://support.polkadot.network/support/solutions/articles/65000098878-how-to-create-a-dot-account"
+            >
+              this guide
+            </a>{' '}
+            to create a {systemChain} account.
```
Comment (statictype) [inline src/ui/components/common/AccountsError.tsx:32]: maybe rephrase or highlight the chain name somehow? It reads weirdly "Follow this guide to create a Contracts"

**Comment by statictype** [comment]
maybe we should add some info about how to drip funds? https://github.com/paritytech/cumulus/blob/master/parachains/runtimes/contracts/contracts-rococo/README.md

**Review by statictype — APPROVED** [review]

**Review by statictype — APPROVED** [review]
