### PR TITLE
fix: #513 sign with injected wallets on local node

### LINKED ISSUE #513: Prompt to unlock account when interacting with actual wallet accounts
**Describe the bug**

When using development accounts (Alice, Bob, etc), I can interact fine with my contract, but when setting to an actual wallet account, sending a contract transaction yields a `Call Error`. Looking at the browser dev console sees the error message of:

```
Error: Cannot sign with a locked key pair
```

**To Reproduce**

1. Go to <https://contracts-ui.substrate.io/>
2. Deploy a contract.
3. Set the Caller to a wallet account.
4. Send a transaction to the contract.

**Expected behavior**

I would expect Polkadot-js Extension will pop up a window to prompt me for password to unlock my keypair.

**Screenshots**

Screenshot 2023-09-03 at 07 01 06

### PR DESCRIPTION
**Pull request by peetzweg**
Resolves #513/#520 by referring to the selected account if it's a testing account or not and acting accordingly.

This is the actual change:
https://github.com/paritytech/contracts-ui/pull/527/files#diff-d22473d5f78c6d4516163586c619fa5d61e960611e085cd39c676ab0afe72e81R41-R53

The rest just got reformatted due to a now shorter line: 
https://github.com/paritytech/contracts-ui/pull/527/files#diff-d22473d5f78c6d4516163586c619fa5d61e960611e085cd39c676ab0afe72e81R56-R93

### CODE REVIEW

File: src/ui/contexts/TransactionsContext.tsx [hunk 1]
```diff
@@ -37,52 +38,59 @@ export function TransactionsContextProvider({
...
+        if (result.isInBlock || result.isFinalized) {
+          const events: Record<string, number> = {};
+
+          result.events.forEach(record => {
+            const { event } = record;
+            const key = `${event.section}:${event.method}`;
+            if (!events[key]) {
+              events[key] = 1;
+            } else {
+              events[key]++;
```
Comment (SkymanOne) [inline src/ui/contexts/TransactionsContext.tsx:66]: I think we need a conditional check here. Is there a range of allowed values?

File: src/ui/contexts/TransactionsContext.tsx [hunk 2]
```diff
@@ -37,52 +38,59 @@ export function TransactionsContextProvider({
...
+            throw new Error(message);
           }
-        },
-      );
+
+          onSuccess && (await onSuccess(result));
+
+          setTxs({ ...txs, [id]: { ...tx, status: TxStatusMap.Success, events } });
+
+          unsub();
```
Comment (SkymanOne) [inline src/ui/contexts/TransactionsContext.tsx:89]: Need a quick comment here.

**Review by SkymanOne — APPROVED** [review]
LGTM! Just few nits.

File: src/ui/contexts/TransactionsContext.tsx (hunk 1 above)
Comment (peetzweg) [reply src/ui/contexts/TransactionsContext.tsx:66]: The code in the `try` block just got reformatted. 
While looking into it, I'm less of a fan how this is done. However, refactoring should be done another day.

The `extrinsic.signAndSend()` call registers a callback, which is called for every state the extrinsic is in. The section you pointed out collects the events from each state. Not in a list but in a map from `event => amount of occurrence`. Weird choice but let's not break things. 🙈

File: src/ui/contexts/TransactionsContext.tsx (hunk 2 above)
Comment (peetzweg) [reply src/ui/contexts/TransactionsContext.tsx]: Made it a bit more clear in [my recent commit](https://github.com/paritytech/contracts-ui/pull/527/commits/8fd0d50c9490e74c31e88d958fd086a9e7b9faad). This part adds the current `tx` as a success to the `txs` map and `unsubscribes` from the submitted `extrinsic.singAndSend()` extrinsic status updates as the work is done here.

But a bit sad the code only seem to care about `finalized` and `inBlock` events. 🤷 

https://github.com/paritytech/contracts-ui/blob/8fd0d50c9490e74c31e88d958fd086a9e7b9faad/src/ui/contexts/TransactionsContext.tsx#L58

File: src/ui/contexts/TransactionsContext.tsx [hunk 3]
```diff
@@ -31,58 +32,68 @@ export function TransactionsContextProvider({
...
+
+            if (result.dispatchError?.isModule) {
+              const decoded = api?.registry.findMetaError(result.dispatchError.asModule);
+              message = `${decoded?.section.toUpperCase()}.${decoded?.method}: ${decoded?.docs}`;
+            }
+
+            onError && onError(result);
+
+            unsubscribe();
+            throw new Error(message);
```
Comment (SkymanOne) [inline src/ui/contexts/TransactionsContext.tsx:85]: Maybe we can provide a brief reason behind transaction failure?

**Review by SkymanOne — COMMENTED** [review]
Looks way cleaner

File: src/ui/contexts/TransactionsContext.tsx (hunk 3 above)
Comment (peetzweg) [reply src/ui/contexts/TransactionsContext.tsx:85]: I lines 77-80 we try to decode the given error with the metadata we have. The raw `result` gets passed along to a potential error handler, `onError` and last but not least we throw a proper Error with a generic or decoded error message. Depending how the rest is implemented the error is caught or an `onError` provided, which then presents the error to the user somehow, either a toast popping up or a failure message. 

I think that's all we could do here. 🤔

Comment (SkymanOne) [reply src/ui/contexts/TransactionsContext.tsx:85]: Ah, my bad, did not notice the error decoding

**Review by SkymanOne — APPROVED** [review]
